# -*- coding: utf-8 -*-
"""data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11l7o2vtTegubtEe0ba4DdC0r79NkYnnr
"""

import pandas as pd
try:
    link = input('Enter csv link of data = ')
    data = pd.read_csv(link)
    print("✅ File loaded successfully!")
    df = pd.DataFrame(data)
except FileNotFoundError:
    print("❌ Error: The file was not found. Please check the path and try again.")

except pd.errors.EmptyDataError:
    print("❌ Error: The file is empty. Upload a dataset with data inside.")

except pd.errors.ParserError:
    print("❌ Error: The file could not be parsed. Check if it's a valid CSV.")

except Exception as e:
    print(f"⚠️ Unexpected error occurred: {e}")

print("Data before cleaning :")
df.info()
print(df.shape)
# Removing Special characters from numeric column so statistics operation can be performed
print("🧾 Cleaning numeric columns...")

for col in df.columns:
    if df[col].dtype == 'object':
        try:
            df[col] = df[col].replace('[^0-9.]', '', regex=True).astype(float)
        except:
            pass

n = df.isnull().sum().sum() #checking for null values
print('There is',n,'null values in our data')

print('Column wise null values =',df.isnull().sum())

df.duplicated()  #checking for duplicate values in our data


df[df.duplicated()] # viewing duplicate rows
num_duplicates = df.duplicated().sum()
if num_duplicates > 0:
    print(f"Found {num_duplicates} duplicates. Dropping them.")
    df.drop_duplicates(inplace=True)
# Dropped duplicate values



ask = input('You want to drop rows which contain null value yes/no = ').lower() #asking user what they want with null value rows

if ask=='yes':
    df.dropna(inplace=True)
elif ask=='no':
    imp = int(input("How do you want to fill missing values? (1 = mean, 2 = median, 3 = mode)"))
    if imp==1:
        df.fillna(df.mean(),inplace=True)
    elif imp==2:
        df.fillna(df.median(),inplace=True)
    elif imp==3:
        df.fillna(df.mode(),inplace=True)
    else:
        print('Invalid choice')
else:
    print('Invalid choice')


print("Data after cleaning")
df.info()
print(df.shape)

#saving cleaned data
save_name = input("Enter name of cleaned file without extension : ")
file_path = f"{save_name}.csv"

try:
    with open(file_path, 'r'):
        overwrite = input(f"⚠️ File '{file_path}' exists. Overwrite? (y/n): ").strip().lower()
        if overwrite != 'y':
            print("❌ File not saved.")
        else:
            df.to_csv(file_path, index=False)
            print(f"✅ Saved as '{file_path}'")
except FileNotFoundError:
    df.to_csv(file_path, index=False)
    print(f"✅ Saved as '{file_path}'")

print("Thanks!!!, For using our script......")

